#!/usr/bin/env bash
set -e
DOTSYS_REPO_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && pwd)"

echo "==> Installing Sway..."

# Package translations vs arch/init.d/sway.sh:
#   sway-contrib      -> grimshot (packaged standalone on Void)
#   xorg-xwayland     -> xorg-server-xwayland
#   autotiling-rs     -> autotiling (python build; same behavior)
#   rofi-wayland      -> rofi (wayland fork was upstreamed in rofi 2.0)
#   swaylock-effects  -> swaylock (AUR-only fork; stock is packaged)
sudo xbps-install -Sy \
  sway swaybg swayidle swaylock \
  grimshot \
  xdg-desktop-portal-wlr xorg-server-xwayland \
  autotiling \
  rofi rofi-calc \
  flameshot \
  wev

# Session wrapper launched by greetd (replaces `uwsm start default`).
# The turnstile D-Bus user service provides the shared session bus, while
# elogind supplies the login session and seat. Sway must not go through
# dbus-run-session because that would spawn a second bus.
sudo tee /usr/local/bin/sway-session >/dev/null <<'EOF'
#!/bin/sh

# Match uwsm's Arch adapter by loading the shared graphical environment.
shared_env="${XDG_CONFIG_HOME:-$HOME/.config}/desktop-session/env"
if [ -r "$shared_env" ]; then
  . "$shared_env"
fi

export XDG_CURRENT_DESKTOP=sway

# Let libseat select elogind's logind backend automatically.
# Sway refuses to start on the proprietary NVIDIA driver without this flag.
if lsmod | grep -q '^nvidia '; then
  exec sway --unsupported-gpu
fi

exec sway
EOF
sudo chmod 755 /usr/local/bin/sway-session

# Environment propagation now lives behind dotfiles' desktop-session seam.
# Remove only the legacy file generated by older versions of this script.
legacy_env_config="${XDG_CONFIG_HOME:-$HOME/.config}/sway/config.d/10-turnstile.conf"
if grep -qx '# Generated by dotsys void/init.d/sway.sh' "$legacy_env_config" 2>/dev/null; then
  rm "$legacy_env_config"
fi

mkdir -p "$HOME/Pictures"
cp -r "$DOTSYS_REPO_HOME/wallpapers" ~/Pictures/
