#!/usr/bin/env bash
set -e
DOTSYS_REPO_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && pwd)"

echo "==> Installing Sway..."

# Package translations vs arch/init.d/sway.sh:
#   sway-contrib      -> grimshot (packaged standalone on Void)
#   xorg-xwayland     -> xorg-server-xwayland
#   autotiling-rs     -> autotiling (python build; same behavior)
#   rofi-wayland      -> rofi (wayland fork was upstreamed in rofi 2.0)
#   swaylock-effects  -> swaylock (AUR-only fork; stock is packaged)
sudo xbps-install -Sy \
  sway swaybg swayidle swaylock \
  grimshot \
  xdg-desktop-portal-wlr xorg-server-xwayland \
  autotiling \
  rofi rofi-calc \
  flameshot \
  wev

# Session wrapper launched by greetd (replaces `uwsm start default`).
# The turnstile dbus user service provides the session bus, so sway must
# NOT go through dbus-run-session (that would spawn a second bus).
sudo tee /usr/local/bin/sway-session >/dev/null <<'EOF'
#!/bin/sh
export XDG_CURRENT_DESKTOP=sway

# Sway refuses to start on the proprietary NVIDIA driver without this flag.
if lsmod | grep -q '^nvidia '; then
  exec sway --unsupported-gpu
fi

exec sway
EOF
sudo chmod 755 /usr/local/bin/sway-session

# Publish the wayland env into the turnstile envdir so user services
# (waybar, kanshi) can reach the compositor. The dotfiles sway config must
# include this directory; see the note below.
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
mkdir -p "$XDG_CONFIG_HOME/sway/config.d"
cat >"$XDG_CONFIG_HOME/sway/config.d/10-turnstile.conf" <<'EOF'
# Generated by dotsys void/init.d/sway.sh
exec_always turnstile-update-runit-env WAYLAND_DISPLAY SWAYSOCK DISPLAY XDG_CURRENT_DESKTOP
EOF

if ! grep -rqs 'config.d' "$XDG_CONFIG_HOME/sway/config" 2>/dev/null; then
  echo "NOTE: add this line to your sway config (dotfiles repo):"
  echo "  include ~/.config/sway/config.d/*"
fi

mkdir -p "$HOME/Pictures"
cp -r "$DOTSYS_REPO_HOME/wallpapers" ~/Pictures/
